### ISSUE TITLE
k-reducto

### ISSUE THREAD

**Issue by AFaugeras** [alakarteio/k-rex#11]
https://github.com/alakarteio/k-simple-state/issues/8#issuecomment-358619109

Ispired by the Harry Potter spell `reducto` [(reference here)](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjey4237-HYAhWMDpoKHVAoCKgQFggoMAA&url=http%3A%2F%2Fharrypotter.wikia.com%2Fwiki%2FReductor_Curse&usg=AOvVaw3-8riAsRq3sE8WhlewZtPS)

**Comment by fabienjuif** [comment]
This is funny :)

But in an other hand this is kinda close to `Redu(x)[cto]`.

**Comment by fabienjuif** [comment]
As @frinyvonnick just say to me: we must have a name that doesn't reference a technical word (like `state` or `redux`)
