### ISSUE TITLE
k-serole

### ISSUE THREAD

**Issue by guillaumecrespel** [alakarteio/k-rex#27]
To cooking anywere !

https://github.com/alakarteio/k-simple-state/issues/8#issuecomment-359797347

![image](https://user-images.githubusercontent.com/26094222/35279681-0400ff46-004e-11e8-8b12-afa5375142de.png)

**Comment by EmrysMyrddin** [comment]
The joke will be dificult to catch in english doesn't it ?

**Comment by guillaumecrespel** [comment]
French touch baby !

**Comment by frinyvonnick** [comment]
C'est pas grave, ça me fait penser à Traefik qui donne des noms de fromages à leur version 👍

**Comment by EmrysMyrddin** [comment]
Sauf que le nom de fromage est le meme en anglais :-P
