### ISSUE TITLE
meta+poll / find a name to the lib

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-rex#8]
Rules:
 - Each comment is a name proposition, vote with 👍 or 👎 
 - The name should not have `redux` in it, so we can change implementation in a near future if we'd like to
 - The name may have a `k-` in prefix but this is not mandatory
 - To comment a proposition
    * open a new thread that reference the comment
    * the new thread should have label `name`
 - I will close the thread when I feel we have a good name

Thank for your help everyone.

@delphinemillet @guillaumecrespel @bpetetot @frinyvonnick @EmrysMyrddin

**Comment by fabienjuif** [comment]
`k-simple-state`

**Comment by AFaugeras** [comment]
`k-reducto`

**Comment by fabienjuif** [comment]
As @frinyvonnick just say to me: we must have a name that doesn't reference a technical word (like `state` or `redux`)

**Comment by fabienjuif** [comment]
`k-zaatar`

**Comment by fabienjuif** [comment]
@delphinemillet @guillaumecrespel @bpetetot @frinyvonnick @EmrysMyrddin

ping for vote, and maybe new idea ? :)

**Comment by bpetetot** [comment]
`k-rex`

**Comment by fabienjuif** [comment]
@delphinemillet @guillaumecrespel @bpetetot @frinyvonnick @EmrysMyrddin @AFaugeras 

bump for vote / propositions :)

**Comment by guillaumecrespel** [comment]
`k-serole`
